backend:
  name: git-gateway
  branch: master
media_folder: source/images
public_folder: /images
collections:
  - name: all_posts
    fields: &ref_0
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
        dateFormat: YYYY-MM-DD
        timeFormat: 'HH:mm:ss'
        format: 'YYYY-MM-DD HH:mm:ss'
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Categories
        name: categories
        widget: list
        required: false
      - label: Body
        name: body
        widget: markdown
        required: false
      - label: Permalink
        name: permalink
        widget: string
        required: false
      - label: Comments
        name: comments
        widget: boolean
        default: true
        required: false
    label: Post
    folder: source/_posts
    create: true
    editor:
      preview: true
  - label: Page
    name: pages
    delete: false
    files:
      - name: 404.html
        label: ''
        file: source/404.html
        editor:
          preview: true
        fields: *ref_0
      - name: categories-index.md
        label: 分类
        file: source/categories/index.md
        editor:
          preview: true
        fields: *ref_0
      - name: tags-index.md
        label: 标签
        file: source/tags/index.md
        editor:
          preview: true
        fields: *ref_0
      - name: s-x-index.html
        label: ''
        file: source/s/x/index.html
        editor:
          preview: true
        fields: *ref_0
